# Generated by Django 3.1.1 on 2020-09-22 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('phone_no', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True, max_length=500, null=True, verbose_name='message')),
                ('transaction_id', models.CharField(max_length=100, verbose_name='transaction ID')),
                ('server_message_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='server message id')),
                ('server_response', models.TextField(blank=True, null=True, verbose_name='server response')),
                ('last_status', models.CharField(max_length=30, verbose_name='last status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='updated at')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
