# Generated by Django 3.1.1 on 2021-03-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=50)),
                ('brand_name', models.CharField(max_length=100)),
                ('generic_name', models.CharField(max_length=500)),
                ('strength', models.FloatField()),
                ('manufactured_by', models.CharField(max_length=500)),
                ('unit_price', models.FloatField()),
                ('indications', models.TextField(blank=True)),
                ('therapheutic_class', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('pharmacology', models.TextField(blank=True)),
                ('doasge_and_administration', models.TextField(blank=True)),
                ('interaction', models.TextField(blank=True)),
                ('contraindications', models.TextField(blank=True)),
                ('side_effects', models.TextField(blank=True)),
                ('pregnancy_and_lactation', models.TextField(blank=True)),
                ('precautions', models.TextField(blank=True)),
                ('storage_conditions', models.TextField(blank=True)),
                ('overdose_effects', models.TextField(blank=True)),
                ('administration', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'medicine',
                'verbose_name_plural': 'medicines',
                'ordering': ('brand_name',),
            },
        ),
    ]
